require_relative 'podspec_versions.rb'

platformVersion = '13.0'
platform :ios, platformVersion

install! 'cocoapods', :disable_input_output_paths => true

ENV['TRIKOT_FRAMEWORK_NAME']='NwadFramework'

target 'iosApp' do
  use_frameworks!

  properties = load_properties('../gradle.properties')

  pod 'SwiftLint'
  pod 'NwadFramework', :path => '../common'
  pod 'Trikot.http', :git => 'git@github.com:mirego/trikot.http.git', :tag => properties['trikot_http_version'], :inhibit_warnings => true
  pod 'Trikot.viewmodels.declarative', :git => 'git@github.com:mirego/trikot.viewmodels.declarative.git', :commit => "b2916c2a7fbb394b2af194d29f1d5ca4eef209d6", :inhibit_warnings => true
  pod 'Trikot.streams', :git => 'git@github.com:mirego/trikot.streams.git', :tag => properties['trikot_streams_version'], :inhibit_warnings => true
  pod 'Trikot.kword', :git => 'git@github.com:mirego/trikot.kword.git', :tag => properties['trikot_kword_version'], :inhibit_warnings => true
  pod 'Kingfisher/SwiftUI', '~> 5.0'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = platformVersion
      end
    end
  end
end
