name: CI

on:
  # Trigger the workflow on push only for the master branch
  push:
    branches:
      - master

  # Trigger the workflow on any pull requests
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: run common check
        run: ./gradlew :common:check

      - name: run android check
        run: ./gradlew :android:check

      - name: run web check
        run: ./gradlew :web:check

      - name: generate code coverage report
        run: ./gradlew :common:jacocoTestReport
